# Generated by Django 4.2.2 on 2025-03-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='boundary',
            field=models.CharField(choices=[('外部', '外部'), ('内部', '内部')], max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('定例', '定例'), ('単件', '単件'), ('長期', '長期')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_progress',
            field=models.CharField(max_length=10),
        ),
    ]
